# Generated by Django 6.0.4 on 2026-04-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
        migrations.RenameModel(
            old_name='Supplies',
            new_name='Supply',
        ),
    ]
