# Generated by Django 6.0.4 on 2026-04-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_states_state_rename_supplies_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
