# Generated by Django 6.0.4 on 2026-04-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_supply_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
